### PR TITLE
Load gist

### PR DESCRIPTION
**Pull request by algomaster99**
Basic functionality of loading gist has been added.
load

### ToDos
- [x] Preview the image of visualization if exists.
- [x] Automatically identify the type of visualization.
- [ ] Change design for displaying the list.

### CODE REVIEW

**Comment by algomaster99** [comment]
### Image preview
Screenshot from 2019-08-05 12-17-32

**Comment by domoritz** [comment]
* [ ] Replace loading spinner with text "Loading your GISTs..."
* [ ] Use actual links in the list
* [ ] List looks weird if there is no title

Screen Shot 2019-08-11 at 2 05 24 PM

* [ ] Visually distinguish private gists
* [ ] "Upload an image with same name as the gist file to" -> the same name
* [ ] Capitalize gist consistently

Screen Shot 2019-08-11 at 2 07 25 PM

**Comment by domoritz** [comment]
Loading doesn't work for me

Screen Shot 2019-08-11 at 2 08 10 PM

**Comment by domoritz** [comment]
Why does the revision get filled in after I click load?

**Comment by domoritz** [comment]
- [ ] Logging in in a new tab should not result in two editors but only one (that is clogged in)

**Comment by algomaster99** [comment]
@domoritz I didn't get the unchecked points above. Can you explain them? Also, please look at the updated changes. Thanks!

**Pull request merged**
