### PR TITLE
Increasing padding around user popup

### LINKED ISSUE #465: more padding around user popup

### PR DESCRIPTION
**Pull request by algomaster99**
Fixes #465 
Screenshot from 2019-08-19 13-34-13

### CODE REVIEW

**Comment by domoritz** [comment]
I'd reduce the top padding to maintain visual balance.

**Comment by domoritz** [comment]
Please update the screenshot when you force push.

**Comment by algomaster99** [comment]
@domoritz Haven't made the changes yet. I will once I do it.

**Comment by algomaster99** [comment]
@domoritz 
Screenshot from 2019-08-19 13-51-56

**Pull request merged**
