### PR TITLE
Fixes vega lite charts rendering twice

### LINKED ISSUE #536: Charts are rendered twice
Right now, we parse Vega-Lite specs twice every time someone hits the `run` button.

### PR DESCRIPTION
**Pull request by adrijshikhar**
Resolves #536

### CODE REVIEW

**Comment by domoritz** [comment]
Can you revert the formatting changes?

**Comment by adrijshikhar** [comment]
eslint fixes were made by pre commit hook. If you want i can remove. And if these linting changes are not required then should we remove the pre commit hooks?

**Comment by domoritz** [comment]
Prettier is configured to use single quotes so I'm not sure why the formatting is incorrect. Can you make sure to install all dependencies with yarn and maybe run `yarn prepare`?

**Comment by adrijshikhar** [comment]
yeah `yarn prepare` fixed it. Thanks. 
So it is a combination of eslint and prettier, linting the code.

**Comment by domoritz** [comment]
Great. I thought `yarn` runs `yarn prepare` but I'm glad this is fixed now.

**Comment by adrijshikhar** [comment]
Yes I did that experiments. It worked.
I will test it again and I will upload a gif .

**Comment by adrijshikhar** [comment]
I will get right on it. Thanks

**Comment by domoritz** [comment]
Thank you @adrijshikhar. I look forward to a working fix for this issue.

**Comment by domoritz** [comment]
@adrijshikhar Would you have time to finish this fix?

**Comment by adrijshikhar** [comment]
I looked into it and i found that, we have to set config when we switch to vega lite. The solution that i was thinking of was that to shift the setting of config from  `parseVegaLite` to `updateConfig`

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/editor/pull/730

**Pull request closed without merging**
