### PR TITLE
Coalesce share modal into export modal

### PR DESCRIPTION
**Pull request by algomaster99**
### Demo
pop

### CODE REVIEW

**Comment by domoritz** [comment]
Thank you for merging the two. Do you think we should make sharing by url the first entry instead of the last?

**Comment by algomaster99** [comment]
@domoritz I think it's fine. Their equal size assert equal importance.

**Comment by domoritz** [comment]
I think people still gravitate to look at the first option first. I'd like sharing to be the first option.

**Comment by algomaster99** [comment]
@domoritz 
Screenshot from 2019-06-30 21-58-32

**Comment by domoritz** [comment]
Thank you!

**Pull request merged**
