### PR TITLE
Keyboard Shortcuts are now shown according to OS

### PR DESCRIPTION
**Pull request by siddhant1**
image

### CODE REVIEW

**Comment by siddhant1** [comment]
@domoritz please verify in mac

**Comment by domoritz** [comment]
Screen Shot 2019-03-15 at 07 12 08

**Comment by domoritz** [comment]
Also note that the command palette in Monaco has shortcuts that we are not covering right now. We should also least document this and tell users how to access the command menu.

Screen Shot 2019-03-15 at 07 13 17

**Comment by siddhant1** [comment]
Cool , let me do it

**Comment by siddhant1** [comment]
Should I add it in the tips section or should I make a note after the shortcuts section?

**Comment by domoritz** [comment]
Note after the shortcuts.

**Comment by domoritz** [comment]
Ping me when this is ready to be merged.

**Comment by siddhant1** [comment]
Oops , forgot about it , will make it ready today.

**Comment by siddhant1** [comment]
Fixed @domoritz !

**Pull request merged**
