### PR TITLE
Fix signal viewer

### PR DESCRIPTION
**Pull request by algomaster99**
Fixes rendering of values. Modified `formatValueLong` function to our own needs.

### Further improvements
- [x] Fix scrolling
- [x] When spec is edited, signals don't change on further actions since component doesn't mount.
- [ ] Write a better function to render signal values

### CODE REVIEW

**Comment by siddhant1** [comment]
I guess the scrolling was already fixed

**Comment by domoritz** [comment]
Wait, was the code to format values in the data table right but it's wrong for signals?

**Comment by algomaster99** [comment]
@domoritz Basically, when the signal value was an object, it was returning a html table. That's why we needed to re-write the function. For other dataTypes, it was working fine. But i think for nested objects it will create an issue so I re wrote the function. Nested objects example: `[{}, {}]`
@siddhant1 There are some fixes like:-
- Horizontal scroll
- When I scroll to bottom, can't see the last entry
- Color of the scroll thumb

**Comment by domoritz** [comment]
What did you do about "Horizontal scroll"?

**Comment by algomaster99** [comment]
@domoritz horizontal scroll is currently disabled somehow

**Comment by domoritz** [comment]
Okay, I want to avoid it but we should not disallow it. Good observation.

**Comment by algomaster99** [comment]
@domoritz 
Scrolling has been fixed :)
scroll

**Comment by algomaster99** [comment]
[Commit](https://github.com/vega/editor/pull/309/commits/f65ab7cf192c13481f1490300aa2c95416f8978d) fixes second checkbox.
Signal listeners were added in componentDidUpdate because if we leave the signal tab opened, and then edit the spec, the signal listeners were added to `prevProps` which caused dysfunction in real-time change of signal values in the table afterwards. And since the component is already mounted, new signal listeners weren't added. So `componentDidUpdate` just adds the signal listener to a new set of `props`.

**Comment by domoritz** [comment]
Notice that I pushed some style changes yesterday so scrolling might already be fixed in Master.

**Comment by algomaster99** [comment]
@domoritz when I rebased master onto branch, scrolling wasn't fixed. I have fixed it in this PR though. One objective remains now, I'll try to optimize the function I have written. I am thinking of using recursion to format signal values.

**Comment by domoritz** [comment]
I think this PR is mixing too many things now. Can you make separate PRs that fix individual bugs? Thanks!

**Comment by algomaster99** [comment]
@domoritz you can review this PR then. The optimization can be left for another PR.

**Comment by algomaster99** [comment]
I'm closing this. I'll make another pull request for the bugs.

**Comment by domoritz** [comment]
Thanks

**Pull request closed without merging**
