### PR TITLE
fix: removed overflow:hidden attribute from full-height-wrapper

### LINKED ISSUE #620: Monaco tooltips should be in foreground.
This is a regression coming from a recent refactor I did. 

Screen Shot 2020-02-19 at 10 04 45

### PR DESCRIPTION
**Pull request by adrijshikhar**
fix #620

### CODE REVIEW

**Comment by domoritz** [comment]
This breaks scrolling. Notice how you cannot scroll large specs anymore when you resize the panels.

Screen Shot 2020-02-19 at 13 52 09

**Comment by domoritz** [comment]
I'm closing this. Please send a new pull request with a fix that preserves scrolling.

**Comment by adrijshikhar** [comment]
> I'm closing this. Please send a new pull request with a fix that preserves scrolling.

ok i will take care of this. thanks

**Comment by domoritz** [comment]
Thank you. This is subtle but you can take a look at the editor last week and see how it worked.

**Comment by adrijshikhar** [comment]
> Thank you. This is subtle but you can take a look at the editor last week and see how it worked.

ok

**Pull request closed without merging**
