### PR TITLE
Update export visualization feature (Experimenting)

### LINKED ISSUE #56: SVG export doesn't work in Firefox
See https://github.com/vega/vega-lite/issues/3603

### PR DESCRIPTION
**Pull request by ydlamba**
This might fix #56.

### CODE REVIEW

**Comment by domoritz** [comment]
You can't save the page anymore now. This means I cannot save the SVG.

screen shot 2018-05-19 at 17 48 25

**Comment by ydlamba** [comment]
We can't even save the page on the deployed version as well. Try `Print` and then `Save as PDF`. That's the only option which I can think as of now.

**Comment by domoritz** [comment]
Hmm, I was sure that we could do this in the past.

**Comment by domoritz** [comment]
Nice, this works!

**Pull request merged**
