### PR TITLE
Vega Docs button's alignment fixed

### PR DESCRIPTION
**Pull request by neeraj3029**
Screenshots:

Before:
Screenshot 2019-03-13 at 7 05 46 AM

After:
Screenshot 2019-03-13 at 7 19 42 AM

### CODE REVIEW

**Comment by neeraj3029** [comment]
@domoritz Please review 😄

**Comment by domoritz** [comment]
Does the error happen in all browsers.

**Comment by neeraj3029** [comment]
@domoritz I observed the button in Safari, Chrome, Firefox. The error exists in all of them.

**Comment by neeraj3029** [comment]
I think you're right. I'll find a better turnaround. Thanks.

**Comment by neeraj3029** [comment]
@domoritz Please review.
GIF-
vega

**Comment by neeraj3029** [comment]
Updated GIF-
vega

**Comment by siddhant1** [comment]
This happenend due to #260  and will be fixed by #270 , no need for an extra pr

**Comment by siddhant1** [comment]
This happened due to leaking of styles applied to generic tags.

**Comment by siddhant1** [comment]
I think we can close this pr for now

**Comment by domoritz** [comment]
Thanks both of you.

**Pull request closed without merging**
