### PR TITLE
Workbench cleanup

### PR DESCRIPTION
**Pull request by zhirzh**
- [x] housekeeping
- [x] replace tslint with eslint

### CODE REVIEW

**Comment by domoritz** [comment]
Thanks! Ping me when this is ready.

**Comment by zhirzh** [comment]
@domoritz adding eslint yields [500+ linting errors](https://pastebin.com/ssiwQ10K) which are mostly react specific (deprecations, best practices, code style prefs etc). After suppressing most of those rules, there are still 100+ errors.
Please have a look at them to prioritize tslint-to-eslint migration.

**Comment by domoritz** [comment]
We should ignore `@typescript-eslint/explicit-function-return-type`, `@typescript-eslint/no-explicit-any`. `@typescript-eslint/no-unused-vars` could be enforced by typescript itself if we wanted to. `@typescript-eslint/explicit-member-accessibility` should be ignored for constructors, I think. I've noticed `import/no-extraneous-dependencies` producing wrong results when you import something specific and `*`. For the other ones, I trust your judgement to either disable the rule or fix the code. Does this help?

**Comment by ganeshpatro321** [comment]
Hello @zhirzh 

The work for switching to eslint from tslint seems pretty good. I was working in this and faced few issues,
My only concern is whether its showing correct wanings/errors or not.

In my case there were few unexpected errors coming up:
Like I kept the no-console property on, and added some console.log() statements in the code, sometimes it was showing the error,  and sometimes it was committing changes.

Plus, when showing up the console error, it also shoed some no-unused-vars errors even if they were used.
You can check my  ```eslintrc``` file [here](https://github.com/ganeshpatro321/editor/blob/toEslint/.eslintrc.js).
And dont forget to update the scripts.

Cheers!

**Comment by zhirzh** [comment]
@domoritz from what I can tell, the errors are broadly of two types:

 - actual bugs/errors
 - stylistic choices, anti-patterns and "best" practices

Since I am running prettier independent of eslint, I can say with certainity that the latter was introduced by eslint-config-airbnb. Removing just that one package reduces the number to a managable ~100 errors.

**Comment by zhirzh** [comment]
Since the project uses now deprecated react features heavily (componentWillReceiveProps, findDOMNode, string refs) I suggest we rollback react to an older version where these methods are safe to use

**Comment by domoritz** [comment]
Why are they not safe to use? Yes, we can change the code but I don't think going to an older version will be better.

**Comment by zhirzh** [comment]
Perhaps I should've been clearer when I said "safe". What I meant was:

- React docs explicitly mark some lifecycle methods unsafe and will drop them in v17. These are:
  - UNSAFE_componentWillMount()
  - UNSAFE_componentWillUpdate()
  - UNSAFE_componentWillReceiveProps()
- React team has shown strong sentiments against [using string refs](https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs) and [overusing](https://reactjs.org/docs/refs-and-the-dom.html#dont-overuse-refs) refs in general
- Moving forward react team introduced a strict mode that [throws a warning on string refs](https://reactjs.org/docs/strict-mode.html#warning-about-legacy-string-ref-api-usage) and outright [deprecated findDomNode in strict mode](https://reactjs.org/docs/react-dom.html#finddomnode)

Maybe you're right about there being no benefit in going to an older version but I see no benefit adopting newer versions either unless the project undergoes a major overhaul.

**Comment by domoritz** [comment]
I think we can update things over time to follow best practices more.

**Comment by domoritz** [comment]
What's left to do before we can merge?

**Comment by domoritz** [comment]
@zhirzh do you want to finish this?

**Comment by zhirzh** [comment]
@domoritz yes I will. it's just that I am running busy this month. sorry for the delay.

**Comment by domoritz** [comment]
No problem. It would be good if you could finish up a piece so we can merge it before we get out of sync.

**Comment by domoritz** [comment]
@zhirzh @siddhant1 can we finish this up?

**Comment by siddhant1** [comment]
Will try to finish this up!

**Comment by siddhant1** [comment]
@domoritz @zhirzh Whats remaining in this one?
And @domoritz , react removed these lifecycle hooks because they are mostly misued and have a very specific use case. Now we have more lifecycle hooks to (kinda) replace the previous ones.

**Comment by domoritz** [comment]
Set the pr to be ready, merge Master, maybe use the Vega Dev config as we have done in q or in Vega-Lite (but this could come later).

**Comment by domoritz** [comment]
It would be great to use https://github.com/vega/vega-lite-dev-config here.

**Comment by domoritz** [comment]
@zhirzh @ydlamba Can we finish this up so that we can merge it?

**Comment by domoritz** [comment]
replaced by https://github.com/vega/editor/pull/484

**Pull request closed without merging**
