### PR TITLE
Updated data viewer on signals

### LINKED ISSUE #173: Use the data change API to update the data viewer

### PR DESCRIPTION
**Pull request by ganeshpatro321**
Fixes #173 

The data viewer is updated if any signal is triggered in the chart.

### CODE REVIEW

**Comment by ganeshpatro321** [comment]
ScreenCast for reference:
dataUpdate

**Comment by ganeshpatro321** [comment]
Shall we remove the refresh button? or keep it for better user experience, if anything wrong happens, or data doesn't come then he can use to refresh the data.
@domoritz

**Comment by domoritz** [comment]
Let's r remove the button. 

Great work!

Just to check. When the data view panel is closed, we don't listen to data changes, right?

**Comment by ganeshpatro321** [comment]
We do listen, as of now, do you want to remove when the panel is closed?

**Comment by domoritz** [comment]
Let's try it for now and see what happens.

**Comment by domoritz** [comment]
Can you remove the refresh button in a follow up?

**Comment by ganeshpatro321** [comment]
Yes, I will look into it and send a PR asap.

**Pull request merged**
