### PR TITLE
Adding Feature: Data Viewer

### LINKED ISSUE #85: Feature to view dataset used in a spec

### PR DESCRIPTION
**Pull request by ydlamba**
**First Draft**
screenshot_20180615_201616
**Status:** Work in Progress
Fixes #85.

### CODE REVIEW

**Comment by domoritz** [comment]
Somehow I cannot brush in http://localhost:8080/#/examples/vega-lite/selection_layer_bar_month.

Broken hover

screen shot 2018-06-26 at 17 25 40

- [ ] make tabs look like in VSCode or remove the line between tab and content.
- [ ] dropdown too large
- [ ] Too much white space
- [ ] It's not just error logs. Rename!

screen shot 2018-06-26 at 17 26 15

Resize should be above the tabs

screen shot 2018-06-26 at 17 29 37

Other

- [ ] Don't use `(...)`
- [ ] How do I access data that's too large?
- [ ] Only show the first 100 rows. Then provide a way to jump to next batch.

**Comment by ydlamba** [comment]
@domoritz I have updated a bunch of things. To proceed further, PR needs your feedback.

**Comment by ydlamba** [comment]
The only thing left is `How do I access data that's too large?`, which will be done in a followup PR.

**Comment by ydlamba** [comment]
PR has been updated.

**Comment by domoritz** [comment]
When the table is narrow, the pager is oddly placed. Do you want to center it?

screen shot 2018-08-01 at 08 57 06

**Comment by domoritz** [comment]
Before we can merge this, we need to deal with `...`. At least we should show a tooltip that says that the field is too large to be displayed. Please use the view API (see JS console).

**Comment by domoritz** [comment]
Sometimes headers are not fully visible

screen shot 2018-08-01 at 09 09 00

**Comment by domoritz** [comment]
- [ ] Data table does not update when the data changes. Doe example, when I brush in a chart, the brush store should update.

**Comment by domoritz** [comment]
- [ ] The state of the data viewer is not saved. When I refresh, the arrow is pointing the wrong way.

**Comment by domoritz** [comment]
- [ ] I think the header of the table should not scroll.

screen shot 2018-08-01 at 09 12 30

**Comment by domoritz** [comment]
- [ ] Large table names overflow the dropdown.

screen shot 2018-08-01 at 09 13 12

**Comment by domoritz** [comment]
Two things and then we can merge

- [ ] horizontal scrolling when the table is too wide
- [ ] use the full height for the table instead of fixing the height

**Pull request merged**
