### PR TITLE
Maximise container width for personal gists

### LINKED ISSUE #520: Fix size of gist list container
To make the size more consistent, let's resize the container with the list in it to take the full width and more height (look how much space is wasted in my screenshot).

Screen Shot 2019-09-30 at 23 47 49

### PR DESCRIPTION
**Pull request by algomaster99**
Fixes #520

### CODE REVIEW

**Comment by domoritz** [comment]
Thanks!

We're still not using the available height when we could.
Screen Shot 2019-10-02 at 09 50 29


Also, on small screens, the layout looks very odd. Can you improve it?

Screen Shot 2019-10-02 at 09 50 22

**Comment by algomaster99** [comment]
@domoritz 
wrap

**Comment by domoritz** [comment]
Does the right side of the popup need to be this wide?

**Comment by algomaster99** [comment]
@domoritz I think the widths of input fields are fixed. Will have to make it flexible.

**Comment by domoritz** [comment]
Let's do that. It would be nice if we split the width in half and at some width move the list above the form as you've shown.

**Comment by algomaster99** [comment]
@domoritz done

**Comment by domoritz** [comment]
Looks good. Now that I've used the gist loading a but more, I think we should fade out the list while we load another one instead of showing "Loading..." to avoid jumps in the UI. What do you think?

**Comment by algomaster99** [comment]
@domoritz like fade out the old one and fade in the new?

**Comment by domoritz** [comment]
I think just while the new list is loading, reduce the opacity of the old list. Nothing facny.

**Pull request merged**
