### PR TITLE
Issue197

### PR DESCRIPTION
**Pull request by ayushnawal**
Issue Solved ! . @domoritz  Please review the PR .
Thanks !

### CODE REVIEW

**Comment by siddhant1** [comment]
Can you look into the linting errors? , Make sure you run yarn lint before committing

**Comment by domoritz** [comment]
#223 is a cleaner approach to this issue. Thanks for the pr, though!

**Comment by ayushnawal** [comment]
yeah ! .. i was having problem with an unwanted commit of a .csv file  .. but now i have fixed it .. Thanks for the consideration !

**Comment by domoritz** [comment]
Thanks for the pr!

**Comment by domoritz** [comment]
It wasn't just the csv. The code is also cleaner.

**Pull request closed without merging**
