### PR TITLE
Prepend $schema to spec using monaco editor action

### LINKED ISSUE #455: Add monaco action to add the $schema URL
This can be useful if you have a spec that doesn't have it yet. Yes, this will also reformat the spec.

### PR DESCRIPTION
**Pull request by algomaster99**
Fixes #455

### CODE REVIEW

**Comment by algomaster99** [comment]
@domoritz If I use compact stringify (basically not pass 2 as a parameter), it will not format the code. It will look like this:
Screenshot from 2019-08-19 13-11-35

Also, how should I add a confirmation dialog?

**Comment by domoritz** [comment]
Use `json-stringify-pretty-compact` and `confirm(...)`.

**Comment by algomaster99** [comment]
@domoritz Context menu?

**Comment by domoritz** [comment]
Screen Shot 2019-08-19 at 10 21 11 AM

**Comment by algomaster99** [comment]
@domoritz Should be above `Clear spec`, `Merge config`, right?

**Comment by domoritz** [comment]
Sure, why not. But in the same group.

**Pull request merged**
