### PR TITLE
Upgrade to react-select-2

### LINKED ISSUE #145: Update react select
To version 2.0

### PR DESCRIPTION
**Pull request by ydlamba**
Fixes #145.

### CODE REVIEW

**Comment by domoritz** [comment]
Why is there space between the items?

screen shot 2018-12-05 at 09 37 42

Why is the popup round?

screen shot 2018-12-05 at 09 37 47

**Comment by ydlamba** [comment]
Both styles came with version 2. This space looks weird to me too. I'm removing it.

**Comment by domoritz** [comment]
Rounded corners at the bottom are okay:

screen shot 2018-12-05 at 09 51 19

**Comment by ydlamba** [comment]
- <kbd>screenshot_20181206_010509</kbd>
- <kbd>screenshot_20181206_010454</kbd>

**Comment by ydlamba** [comment]
<kbd>screenshot_20181206_021644</kbd>
<kbd>screenshot_20181206_021524</kbd>
Looks good to me.

**Pull request merged**
