### PR TITLE
Extracted share and export modals

### PR DESCRIPTION
**Pull request by ganeshpatro321**
Towards #156

### CODE REVIEW

**Comment by domoritz** [comment]
@siddhant1 can you help review this?

**Comment by domoritz** [comment]
Hmm, this is just one modal extracted rather than also making the modal itself a shared component. Do you think it makes sense to do that?

**Comment by ganeshpatro321** [comment]
Its better to extract components and keep them inside the header directory itself. It will help for better understanding of the file as well as reducing the header file size.

What do you think @siddhant1 ?

**Comment by siddhant1** [comment]
> @siddhant1 can you help review this?

Sure

> Its better to extract components and keep them inside the header directory itself. It will help for better understanding of the file as well as reducing the header file size.

Makes sense , Since we are following container-presentor approach, we can make `HEADER` component our container and present other components inside it.

**Comment by domoritz** [comment]
@ganeshpatro321 Please share a summary of our discussion on slack so we document it here.

**Pull request merged**
