### PR TITLE
Refactored run button styles

### LINKED ISSUE #436: Run button has too little space on small screens
There needs to be more padding on the right. 

Screen Shot 2019-08-06 at 10 20 16 AM

### PR DESCRIPTION
**Pull request by siddhant1**
Closes #436

### CODE REVIEW

**Comment by domoritz** [comment]
I think 

```css
.split-button {
    width: 80px;
}
```

is sufficient, no?

**Comment by siddhant1** [comment]
Doesn't work for me! it messes up the styles

**Comment by siddhant1** [comment]
yup! it works

**Comment by domoritz** [comment]
I'd like to encourage you to try to fix things by deleting code/modifying code rather than adding more ;-)

**Comment by siddhant1** [comment]
Prev:
image
After:
image

**Comment by domoritz** [comment]
Why do we need the important? I didn't need it when I modified things live in the browser.

**Comment by siddhant1** [comment]
It was already there in media queries  , so I thought it had a purpose! Should I remove both of them?

**Comment by domoritz** [comment]
I guess it's needed.

**Pull request merged**
