### PR TITLE
Fix positioning of report button

### PR DESCRIPTION
**Pull request by algomaster99**

### CODE REVIEW

**Comment by siddhant1** [comment]
image
Good most of the time but not sure abut larger res, can we not do it with position:absolute and parent being relative

**Comment by algomaster99** [comment]
@siddhant1 I will try doing it with `position: absolute` and `position: relative`.

**Comment by domoritz** [comment]
Let's use absolute positioning. It's more reliable.

**Comment by algomaster99** [comment]
@siddhant1 Your suggestion to remote `position: relative` from `.modal-body` worked. Thanks!

**Pull request merged**
