### PR TITLE
Added Warning count in log tab (fixes #147)

### LINKED ISSUE #147: Show warning count in logger tab header
Otherwise it's impossible for users to know that there are warnings when they use the data viewer.

### PR DESCRIPTION
**Pull request by siddhant1**
ref #147 
Capture

### CODE REVIEW

**Comment by domoritz** [comment]
Sweet. Ist ist enough to put the count in the store?

**Comment by siddhant1** [comment]
> Sweet. Ist ist enough to put the count in the store?

Didn't get it , Can you explain? redux store?

**Comment by domoritz** [comment]
Sorry, I meant props. Instead of retuning the logs in the end, you could just return the count, no?

**Comment by siddhant1** [comment]
Yes , I think I can make another entry in the reducer , will check and confirm if that gives a performance boost

**Comment by domoritz** [comment]
It probably doesn't matter but I like to keep interfaces lean.

**Comment by siddhant1** [comment]
Ok!

**Comment by siddhant1** [comment]
image
I think we can't access the warns property, so i can't put it inside a war named logsCount

**Comment by domoritz** [comment]
We should probably also show errors and.makenit red when there is an error (or even automatically open the error panel).

**Comment by siddhant1** [comment]
Sounds good !

**Comment by algomaster99** [comment]
@domoritz Accessing length of `warn` isn't possible since it is a private variable in `logger.ts`. I think current solution is the best possible way.

**Comment by domoritz** [comment]
I don't get it. We already run `({(this.props.warningsLogger as any).warns.length})` so why can't we use this earlier?

**Comment by siddhant1** [comment]
Maybe we have to create a copy of the currlogger and then put the value inside logsCount , or maybe the redux connect is made that way to avoid the typings , or it makes a copy of the object and send us

**Pull request merged**
