### PR TITLE
Used bindActionCreators

### PR DESCRIPTION
**Pull request by ganeshpatro321**
Refactored

### CODE REVIEW

**Comment by algomaster99** [comment]
@ganeshpatro321 Thanks for giving your time to this issue. :) But this was a good-first-issue and was intended to be solved by new contributors. You're quite experienced with the code base so I would recommend you to solve some major issues.
But obviously, if a good-first-issue remains stale for some time, one may fix it.

**Comment by ganeshpatro321** [comment]
@algomaster99 

Thats right, we can close this and keep the issue open.
I did this to keep the code maintained and updated!

cheers.

**Comment by algomaster99** [comment]
@ganeshpatro321 no need of closing this. People can use this as a reference to fix the whole code :)

**Comment by domoritz** [comment]
Thank you for the fixes! This will make our typings much safer.

**Pull request merged**
