### PR TITLE
Reset localStorage

### PR DESCRIPTION
**Pull request by ganeshpatro321**
Created a route "localhost:8080/reset.html", with a button to clear the local storage.
We weren't able to access the app component, so had to create a ".html"  file to reset things.

This can be considered as a WIP pr, we need to update the URLs and may be have automated things i.e., remove button before merging.

@domoritz Please review.

### CODE REVIEW

**Comment by ganeshpatro321** [comment]
Screencast:

reset

**Comment by domoritz** [comment]
I suggested to just add a route. Why did you decide to make a new age instead?

**Comment by ganeshpatro321** [comment]
We aren't able to access the current age when the browser crashes, so I had to create a new age to clear the localStorage.

Can we access it @domoritz 
Correct me if I am wrong.

**Comment by algomaster99** [comment]
@ganeshpatro321 We can clear the site data using this
Screenshot from 2019-03-25 22-30-40

**Comment by siddhant1** [comment]
I personally suggest moving from localstorage API , but a temporary solution would be to tell the user to clear the localstorage himself rather than another route.

**Comment by ganeshpatro321** [comment]
I appreciate you attention guys,

@algomaster99 that's basic, but we wanted a easier way for the user to clear storage.

@siddhant1 yes, but that won't be a good user experience.

Our idea was to have a route which will clear the localStorage and redirect to the home page of editor.

**Comment by domoritz** [comment]
Replaced by bfcac6b

**Pull request closed without merging**
