### PR TITLE
Fix resizing of compiled spec pane

### LINKED ISSUE #316: Cannot open vega panel
editor

### PR DESCRIPTION
**Pull request by algomaster99**
Fixes #316 

resize

### CODE REVIEW

**Comment by ganeshpatro321** [comment]
Nicely debugged. @algomaster99

**Comment by domoritz** [comment]
Well done! Let's not make it 0 so the top editor does not just disappear.

**Comment by algomaster99** [comment]
@domoritz Will do. How much though?

**Comment by domoritz** [comment]
Never mind, I thought this was the Vega-Lite editor pane.

**Pull request merged**
