### PR TITLE
Dom/nesterone/180

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by domoritz** [comment]
@nesterone can you check this?

**Comment by nesterone** [comment]
Yep, will take a look tomorrow

**Comment by domoritz** [comment]
@nesterone friendly ping

**Comment by domoritz** [comment]
I'm going to merge this. Please let me know if you see any issues.

**Comment by nesterone** [comment]
Hi, @domoritz 
Looks like you've already merged that one, sorry, just missed that issue, if that's important  plz log as separate task

Would be glad if you would point me to next issue to work on

**Pull request merged**
