### PR TITLE
Position example modal to center

### LINKED ISSUE #75: Weird positioning of example modal
screenshot_20180518_194744

### PR DESCRIPTION
**Pull request by ydlamba**
Fixes #75.

### CODE REVIEW

**Comment by domoritz** [comment]
How does this fix the issue?

**Comment by ydlamba** [comment]
Now, it's fixed on all standard resolutions.

**Comment by domoritz** [comment]
Can you exain why?

**Comment by ydlamba** [comment]
There are many ways to solve this. I tested this one. It's working.

**Pull request merged**
