### PR TITLE
Reposition horizontal scrollbar in tables

### PR DESCRIPTION
**Pull request by algomaster99**
Remove padding between table and horizontal scrollbar in tables

scroll

### CODE REVIEW

**Comment by algomaster99** [comment]
This is only for Google Chrome. Scrolling, overall, has to be fixed for firefox (scrollbars don't appear) and safari ([formatting](https://github.com/vega/editor/issues/284)).

**Comment by algomaster99** [comment]
@domoritz Okay, I will look into this.

**Comment by algomaster99** [comment]
@domoritz I can see the vertical scrollbar. Can you share the spec so I can reproduce this?

**Comment by domoritz** [comment]
https://vega.github.io/editor/#/examples/vega-lite/histogram should do it.

**Comment by algomaster99** [comment]
@domoritz I am not facing this issue. Were you trying on some other browser other than Chrome?
scroll

**Comment by domoritz** [comment]
I'm on chrome and I just tried it again and it still does not work. It works great on master.

**Comment by algomaster99** [comment]
@domoritz Are we having different versions again? What is yours?

**Comment by domoritz** [comment]
I'm on 75.0.3770.38

**Comment by algomaster99** [comment]
@domoritz It is a version issue. I'll upgrade mine and test it.

**Comment by domoritz** [comment]
@algomaster99 Can you finish this or close the PR?

**Comment by algomaster99** [comment]
@domoritz I am closing this for now. Might look into this later.

**Pull request closed without merging**
