### PR TITLE
Remove unsafe lifecycle

### LINKED ISSUE #446: remove unsafe react lifecycle methods
Screen Shot 2019-08-11 at 1 51 59 PM

### PR DESCRIPTION
**Pull request by shakti97**
Fix #446

### CODE REVIEW

**Comment by siddhant1** [comment]
I will run lint over it

**Comment by shakti97** [comment]
sure

**Comment by domoritz** [comment]
Let me know when this is done. Thanks!

**Comment by shakti97** [comment]
@domoritz i resolved the issue which you mentioned, please check and if required any changes let me know :)

**Comment by domoritz** [comment]
Thank you @shakti97!

**Pull request merged**
