### PR TITLE
Condition refactored

### PR DESCRIPTION
**Pull request by ganeshpatro321**

### CODE REVIEW

**Comment by ganeshpatro321** [comment]
Fixes #317

**Comment by domoritz** [comment]
That doesn’t look like the right fix. Instead, we should use the 2nd entry when the list has more than one item but the first when there Is only one.

**Comment by ganeshpatro321** [comment]
Changes done accordingly. @domoritz

**Comment by ganeshpatro321** [comment]
Ohh, dint see the fix. Closing this

**Pull request closed without merging**
