### PR TITLE
Browser crashing bug solved

### LINKED ISSUE #282: Data viewer makes the browser crash
I see that https://github.com/vega/editor/issues/173 is merged, but if I try this locally with example https://vega.github.io/editor/#/examples/vega-lite/bar it doesn't perform well. Actually my browser just crashes. 
See the following screencast
Kapture 2019-03-14 at 20 52 06

Not sure if I miss something?

### PR DESCRIPTION
**Pull request by ganeshpatro321**
This PR fixes #282 

Please review @domoritz

### CODE REVIEW

**Comment by domoritz** [comment]
Can you explain it, please?

**Comment by ganeshpatro321** [comment]
Previously the datalisteners were added multiple times for the same data source which caused the page to render multiple times. Now we are checking whether the listener for that particular data source is present or not and then adding the listener.

There was such condition, on 10th or 15th click, the page was rerendering some thousand of times, which caused the web page to crash.

@domoritz

**Comment by domoritz** [comment]
This is not a good fix. We should unregister eventlisteners or ignore events better. It's also not good to use a list to check for duplicates. Better use an object.

**Comment by ganeshpatro321** [comment]
Ohh I see, I will update it.
I tried removing event, in fact, I did, but still I had to check through a list, to get the work done. I will look into it again and update the PR asap. @domoritz

**Comment by ganeshpatro321** [comment]
Removed listeners, please review @domoritz

**Comment by domoritz** [comment]
Wait, so of you together the listener and not remove it from the list, don't we forget to reregister it later?

**Comment by ganeshpatro321** [comment]
No it won't, I also had the same confusion we are clearing the whole list. That won't be a problem @domoritz.

**Comment by domoritz** [comment]
Why do we need a list now? Shouldn't we always have exactly one listener at a time?

**Comment by ganeshpatro321** [comment]
We need a list, because the listener is removed when the data source changes, but on different signal like changing the values we need the list to verify is there any listener. @domoritz

**Comment by domoritz** [comment]
Changing what values?

**Comment by ganeshpatro321** [comment]
Let me share a screencast which will make things clear.

**Comment by domoritz** [comment]
Thanks! I'm a bit confused about all of this and it seems like a hack on top of a hack.

**Comment by ganeshpatro321** [comment]
It is quite simple @domoritz 

dataSourceChange

The above recording shows the change of data source, or change of category, in this case while changing we are removing and adding data listeners.

signal

This recording shows signal triggerings, here the need of list comes in, which checks if there is listener present for that particular data, if yes then no more listener will be added and if no, the listener will be added.

**Comment by domoritz** [comment]
Correct me if I'm doing but I think we only need a single listener at a time. The listener is for the datasets the user is looking at right now.

**Comment by ganeshpatro321** [comment]
No @domoritz

The listener is taking category wise data source as inputs. For ex, the above example has no. Of data sources equal to no of categories present in drop down.

**Comment by domoritz** [comment]
Yeah, but we don't have to listen to data sources that the user has not currently selected. Does that make sense?

**Comment by ganeshpatro321** [comment]
No that doesn't make any sense and we aren't listening to data source that user has not selected.

**Comment by domoritz** [comment]
> The listener is taking category wise data source as inputs. For ex, the above example has no. Of data sources equal to no of categories present in drop down.

I guess I'm not understanding this then. Could you help me understand this? Sorry for being so pedantic but I'd like us to get the design right.

**Comment by ganeshpatro321** [comment]
Sure @domoritz

Give me some time, I think we can avoid using lists and instead use a Boolean. I will try it out and if that works it will be easier to understand.
I will message you asap.

**Comment by domoritz** [comment]
Replaced by https://github.com/vega/editor/pull/302

**Pull request closed without merging**
