### PR TITLE
Upgrade to Vega 4 rc-3

### PR DESCRIPTION
**Pull request by ydlamba**

### CODE REVIEW

**Comment by domoritz** [comment]
Why have all the images changed?

**Comment by ydlamba** [comment]
Running `yarn generate-example-images` changed them. They shouldn't change, right? It might be a problem with my setup.

**Comment by ydlamba** [comment]
I didn't generate the images as all of them are changing for me. You need to do that.

**Comment by domoritz** [comment]
Okay. They will be built on travis so let's just leave it for now.

**Pull request merged**
